deploy PROD:
  stage: deploy
  image:  
   name: amazon/aws-cli
   entrypoint: [""]
  script:
    - aws --version
    - aws s3 rm s3://$S3_BUCKET --recursive
    - aws s3 cp ./ s3://$S3_BUCKET --recursive